image: ubuntu:latest

stages:
  - pipeline

variables:
  DEPLOY_TIMEOUT: 240
  GIT_HTTPS_PATH: "https://${GIT_NAME}:${GIT_HTTPS_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"

packageRetrieval:
  stage: pipeline
  rules:
    - if: $PACKAGE_NAME && $CI_PIPELINE_SOURCE == 'schedule' && $JOB_NAME == 'metadataRetrieval'
      when: always
    - when: never
  allow_failure: false
  before_script:
    - apt-get update
    - apt-get install -y curl git
    - curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
    - apt-get install -y nodejs
    - npm install --global @salesforce/cli@latest
    - sf version --verbose --json
    - git fetch -q
    - git config user.name "${GIT_NAME}"
    - git config user.email "${GIT_USER_NAME}@noreply.${CI_SERVER_HOST}"
    - git checkout -q $CI_COMMIT_BRANCH
    - git pull --ff -q
  script:
    - echo $ORG_AUTH_URL | sf org login sfdx-url --set-default --sfdx-url-stdin
    - source ./scripts/bash/retrieve_packages.sh
  # Cleanup, switch back to the SHA that triggered this pipeline and delete local branches
  after_script:
    - git -c advice.detachedHead=false checkout -q $CI_COMMIT_SHORT_SHA
    - git branch -D $CI_COMMIT_BRANCH
  tags: 
    - aws,prd,us-west-2
